### ISSUE TITLE
the virtual object tracked by Hiro marker is not stable

### ISSUE THREAD

**Issue by mudusun** [qian256/HoloLensARToolKit#10]
Does anybody have the same problem that the virtual object tracked by Hiro marker is not stable. When I remove the marker, the object will stay of course. But when I move my camera to other place and come back, the object disappeared. The object can jump any random place. I don't know why. But the kanji marker tracked is very stable. When I remove the marker, move the camera somewhere and come back, the cube is stay there. Who can tell me why?

**Comment by qian256** [comment]
Probably because your video background contains some distracting objects, that are similar to the pattern of Hiro. The tracking of the two markers are performed exactly same.
You can also train your own pattern marker following this link: [ARToolKit Marker Training](https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training)
