### ISSUE TITLE
Scaling between Unity and Hololens display

### ISSUE THREAD

**Issue by araujokth** [qian256/HoloLensARToolKit#28]
Hi, was wondering what is the scaling applied to convert between the object defined in Unity and displayed in the Hololens? For example, if the marker cube is changed to another size, how can I change it in Unity so that it becomes with the correct dimensions when displayed in the Hololens?

**Comment by qian256** [comment]
**Ideally** the scale between real objects and Unity virtual objects should be 1. But it is not often the case. If you just want to scale down the virtual object, you should have a dummy object under the scene_root object and acts as parent for the virtual object, because the ARUWPMarker script will update the transform of the scene_root object at runtime.
